org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[1,)

mod_id=tobacconistmod
mod_name=Tobacconist
mod_license=All Rights Reserved
mod_version=3.0.0-neoforge-1.21.1
mod_group_id=com.diggydwarff.tobacconistmod
mod_authors=diggydwarff
mod_description=Tobacconist is a mod that facilitates the cultivation and production of tobacco and related smokables for your Minecraft world.

jei_version=19.27.0.336
curios_version=9.5.1+1.21.1
patchouli_version=1.21.1-93-NEOFORGE
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
create_runtime_enabled=true
