package com.diggydwarff.tobacconistmod.event;

import com.diggydwarff.tobacconistmod.TobacconistMod;
import com.diggydwarff.tobacconistmod.block.custom.DoubleHookahBlock;
import com.diggydwarff.tobacconistmod.block.custom.HookahBlock;
import com.diggydwarff.tobacconistmod.block.entity.HookahEntity;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.DoubleBlockHalf;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.entity.EntityJoinLevelEvent;
import net.neoforged.neoforge.event.level.BlockDropsEvent;
import net.neoforged.neoforge.event.level.BlockEvent;

import java.util.HashMap;
import java.util.Map;
import java.util.WeakHashMap;

/**
 * Hookah break/drop handling.
 *
 * Creative breaks must behave like vanilla Creative: remove the block and its stored
 * contents without creating any item entities. Legitimately dropped Hookah items remain
 * invulnerable to environmental damage as before.
 */
@EventBusSubscriber(modid = TobacconistMod.MODID)
public final class HookahDropProtectionEvents {
    private HookahDropProtectionEvents() {}

    /**
     * Short-lived position markers are a final guard for two-block Hookahs. The partner
     * half can be removed by a neighbor update without carrying the original player as
     * the loot breaker, so checking BlockDropsEvent#getBreaker alone is not sufficient.
     */
    private static final Map<ServerLevel, Map<BlockPos, Long>> CREATIVE_BREAK_POSITIONS = new WeakHashMap<>();
    private static final long CREATIVE_BREAK_GUARD_TICKS = 2L;

    @SubscribeEvent
    public static void suppressCreativeHookahContents(BlockEvent.BreakEvent event) {
        if (!event.getPlayer().getAbilities().instabuild || !(event.getLevel() instanceof ServerLevel level)) {
            return;
        }

        BlockState state = event.getState();
        boolean tall = state.getBlock() instanceof DoubleHookahBlock;
        if (!tall && !(state.getBlock() instanceof HookahBlock)) {
            return;
        }

        BlockPos lowerPos = event.getPos();
        if (tall && state.hasProperty(DoubleHookahBlock.HALF)
                && state.getValue(DoubleHookahBlock.HALF) == DoubleBlockHalf.UPPER) {
            lowerPos = lowerPos.below();
        }

        BlockEntity blockEntity = level.getBlockEntity(lowerPos);
        if (blockEntity instanceof HookahEntity hookah) {
            hookah.clearContentsForCreativeBreak();
        }

        markCreativeBreak(level, lowerPos);
        if (tall) {
            markCreativeBreak(level, lowerPos.above());
        }

        // Do not cancel the break and do not remove blocks manually here. Let the normal
        // player break lifecycle remove them exactly once; the drop guards below suppress
        // any loot generated by either half.
    }

    @SubscribeEvent
    public static void suppressCreativeHookahBlockDrops(BlockDropsEvent event) {
        if (!(event.getBreaker() instanceof net.minecraft.world.entity.player.Player player)
                || !player.getAbilities().instabuild) {
            return;
        }

        if (isHookah(event.getState())) {
            event.getDrops().clear();
            event.setDroppedExperience(0);
            event.setCanceled(true);
        }
    }

    @SubscribeEvent
    public static void protectDroppedHookahs(EntityJoinLevelEvent event) {
        if (!(event.getEntity() instanceof ItemEntity itemEntity)
                || !(itemEntity.getItem().getItem() instanceof BlockItem blockItem)
                || !isHookah(blockItem.getBlock().defaultBlockState())) {
            return;
        }

        // Absolute creative-break guard. This catches loot spawned by the secondary half
        // of a tall Hookah even when that teardown has no Player attached as the breaker.
        if (event.getLevel() instanceof ServerLevel serverLevel
                && wasJustBrokenInCreative(serverLevel, itemEntity.blockPosition())) {
            event.setCanceled(true);
            return;
        }

        // Normal dropped Hookah items should not be destroyed by fire/explosions/etc.
        itemEntity.setInvulnerable(true);
    }

    private static boolean isHookah(BlockState state) {
        return state.getBlock() instanceof HookahBlock || state.getBlock() instanceof DoubleHookahBlock;
    }

    private static void markCreativeBreak(ServerLevel level, BlockPos pos) {
        CREATIVE_BREAK_POSITIONS
                .computeIfAbsent(level, ignored -> new HashMap<>())
                .put(pos.immutable(), level.getGameTime());
    }

    private static boolean wasJustBrokenInCreative(ServerLevel level, BlockPos itemPos) {
        Map<BlockPos, Long> positions = CREATIVE_BREAK_POSITIONS.get(level);
        if (positions == null || positions.isEmpty()) {
            return false;
        }

        long now = level.getGameTime();
        positions.entrySet().removeIf(entry -> now - entry.getValue() > CREATIVE_BREAK_GUARD_TICKS);

        // Block drops spawn at/very near the broken position. Check vertical neighbors too
        // because the two-block partner can be the source of the item entity.
        return positions.containsKey(itemPos)
                || positions.containsKey(itemPos.below())
                || positions.containsKey(itemPos.above());
    }
}
